version: '3.8'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - qats

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "24224:24224"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - qats
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - qats
    depends_on:
      - elasticsearch

  jenkins:
    image: jenkins/jenkins:2.235.2-lts-centos7
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: qats-jenkins
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./jenkinsVolume:/var/jenkins_home
    networks:
      - qats
    depends_on:
      - elasticsearch

  jira:
    image: atlassian/jira-software:8.12.0-EAP01-jdk11
    user: root
    ports:
      - 8081:8080
    container_name: qats-jira
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./jiraVolume:/var/atlassian/application-data/jira
    networks:
      - qats
    depends_on:
      - elasticsearch

volumes:
  jenkinsVolume:
  bambooVolume:
  jiraVolume:

networks:

  qats:
    driver: bridge
